- name: Basic Handler Playbook
  hosts: all
  become: true
  vars:
    packages:
      - curl
      - git
      - vim

  tasks:
    - name: Install package
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      notify: "{{ item }} installed"
      loop: "{{ packages }}"

  handlers:
    - name: curl installed
      ansible.builtin.debug:
        msg: "curl was installed"
    - name: vim installed
      ansible.builtin.debug:
        msg: "vim was installed"
    - name: git installed
      ansible.builtin.debug:
        msg: "git was installed"
